# Generated by Django 4.1.7 on 2023-03-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagcategory',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='historicaltag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tags.tag'),
        ),
        migrations.DeleteModel(
            name='HistoricalTagCategory',
        ),
        migrations.DeleteModel(
            name='TagCategory',
        ),
    ]
