# Generated by Django 4.1.7 on 2023-03-23 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_historicaltagcategory_historicaltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
