# Generated by Django 4.1.7 on 2023-03-14 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
