# Generated by Django 4.1.7 on 2023-03-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
        ('tags', '0003_alter_tag_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tagcategory',
            old_name='label',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='from_extension',
        ),
        migrations.RemoveField(
            model_name='tagcategory',
            name='from_extension',
        ),
        migrations.AddField(
            model_name='tag',
            name='extension',
            field=models.ForeignKey(blank=True, help_text='The extension that this tag belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='extension',
            field=models.ForeignKey(blank=True, help_text='The extension that this tag category belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='extensions.extension'),
        ),
    ]
