# Generated by Django 4.1.7 on 2023-03-15 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='profile',
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(default='default purpose', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentprofile',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'sepa')], default='transfer', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
