# Generated by Django 4.1.7 on 2023-04-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_historicalinvoice_historicalitemtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itementry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The amount of units of the item.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.itemtypecategory'),
        ),
    ]
