# Generated by Django 4.1.7 on 2023-03-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
        ('payments', '0002_alter_historicalpayment_date_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='extension',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='extension',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='payment',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extensions.extension'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extensions.extension'),
        ),
    ]
