# Generated by Django 4.1.9 on 2023-06-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_historicalpaymentprofile_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinvoice',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='date_created',
        ),
    ]
