# Generated by Django 4.1.7 on 2023-03-17 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_paymenttype_alter_historicalpayment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
