# Generated by Django 4.1.7 on 2023-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_historicalsubscription_historicalpaymentprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentprofile',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'transfer'), ('sepa', 'sepa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentprofile',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'transfer'), ('sepa', 'sepa')], max_length=30),
        ),
    ]
