# Generated by Django 4.1.7 on 2023-03-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpayment',
            old_name='user',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='historicalsubscription',
            old_name='user',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='payer',
        ),
    ]
