# Generated by Django 4.1.7 on 2023-03-22 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_rename_user_historicalpayment_payer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
