# Generated by Django 4.1.7 on 2023-02-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_user_events_delete_event'),
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('component_name', models.CharField(max_length=255)),
                ('order', models.FloatField(default=1)),
                ('blocked_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_role', to='users.role')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensions.extension')),
                ('required_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_role', to='users.role')),
            ],
            options={
                'unique_together': {('name', 'extension')},
            },
        ),
    ]
