# Generated by Django 4.1.7 on 2023-03-02 15:35

import collectivo.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensions', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('component_name', models.CharField(max_length=255)),
                ('order', models.FloatField(default=1)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensions.extension')),
                ('requires_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('name', 'extension')},
            },
            bases=(models.Model, collectivo.utils.models.RegisterMixin),
        ),
    ]
