# Generated by Django 4.1.7 on 2023-02-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTile',
            fields=[
                ('tile_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('component_name', models.CharField(max_length=255)),
                ('order', models.FloatField(default=1)),
                ('blocked_role', models.CharField(max_length=255, null=True)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensions.extension')),
            ],
        ),
    ]
