# Generated by Django 4.1.7 on 2023-03-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardtile',
            old_name='component_name',
            new_name='component',
        ),
    ]
