# Generated by Django 4.1.9 on 2023-06-20 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coresettings_display_project_description_and_more'),
        ('dashboard', '0004_remove_dashboardtile_requires_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtile',
            name='requires_not_perm',
            field=models.ForeignKey(blank=True, help_text='If set, the object will only be displayed to users without this permission.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requires_not_perm', to='core.permission'),
        ),
        migrations.AddField(
            model_name='historicaldashboardtile',
            name='requires_not_perm',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If set, the object will only be displayed to users without this permission.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.permission'),
        ),
        migrations.AlterField(
            model_name='dashboardtile',
            name='requires_perm',
            field=models.ForeignKey(blank=True, help_text='If set, the object will only be displayed to users with this permission.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requires_perm', to='core.permission'),
        ),
        migrations.AlterField(
            model_name='historicaldashboardtile',
            name='requires_perm',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If set, the object will only be displayed to users with this permission.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.permission'),
        ),
    ]
