# Generated by Django 4.1.9 on 2023-06-20 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
        ('dashboard', '0005_dashboardtile_requires_not_perm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtilebutton',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='historicaldashboardtilebutton',
            name='extension',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='extensions.extension'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardtilebutton',
            unique_together={('name', 'extension')},
        ),
    ]
