# Generated by Django 4.1.7 on 2023-03-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0003_remove_membershipcard_membership_and_more'),
        ('payments', '0002_alter_paymentprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPayments',
            fields=[
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payments', serialize=False, to='memberships.membership')),
                ('fees_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_fees', to='payments.subscription')),
                ('shares_payments', models.ManyToManyField(blank=True, related_name='membership_shares', to='payments.payment')),
            ],
        ),
    ]
