# Generated by Django 4.1.7 on 2023-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayments',
            name='shares_signed',
            field=models.IntegerField(default=0),
        ),
    ]
