# Generated by Django 4.1.5 on 2023-01-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_member_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emaildesign')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(null=True)),
                ('status', models.CharField(choices=[('working', 'working'), ('success', 'success'), ('failure', 'failure')], default='working', max_length=255)),
                ('status_message', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emaildesign')),
                ('recipients', models.ManyToManyField(to='members.member')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate')),
            ],
        ),
    ]
