# Generated by Django 4.1.7 on 2023-03-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAutomationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique='True')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('success', 'success'), ('failure', 'failure')], default='draft', max_length=10)),
                ('status_message', models.CharField(max_length=255, null=True)),
                ('sent', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique='True')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailAutomation',
            fields=[
                ('trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emails.emailautomationtrigger')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique='True')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emaildesign')),
            ],
        ),
    ]
