# Generated by Django 4.1.7 on 2023-03-15 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
        ('extensions', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='tag',
            field=models.ForeignKey(help_text='This tag will be added to recipients if campaign is sent.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='extension',
            field=models.ForeignKey(blank=True, help_text='The extension that created this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='recipients',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate'),
        ),
    ]
