# Generated by Django 4.1.4 on 2023-01-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailbatch',
            old_name='sent',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='emailbatch',
            old_name='email',
            new_name='template',
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='status',
            field=models.CharField(choices=[('working', 'working'), ('success', 'success'), ('failed', 'failed')], default='success', max_length=255),
            preserve_default=False,
        ),
    ]
