# Generated by Django 4.1.4 on 2023-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_rename_sent_emailbatch_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='status_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
