# Generated by Django 4.1.5 on 2023-01-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailbatch_status_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailbatch',
            name='template',
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
