# Generated by Django 4.1.5 on 2023-01-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_remove_emailbatch_template_emailbatch_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='emailbatch',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emailbatch',
            name='status',
            field=models.CharField(choices=[('working', 'working'), ('success', 'success'), ('failed', 'failed')], default='working', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailbatch',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emaildesign'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emaildesign'),
        ),
    ]
