# Generated by Django 4.1.7 on 2023-02-23 10:52

import django.db.models.deletion
from django.db import migrations, models

import collectivo.utils.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extensions", "0001_initial"),
        ("users", "0002_remove_user_events_delete_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[("component", "component"), ("link", "link")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "action_target",
                    models.CharField(
                        choices=[("main", "main"), ("blank", "blank")],
                        default="main",
                        max_length=50,
                    ),
                ),
                (
                    "component_name",
                    models.CharField(max_length=255, null=True),
                ),
                ("link_source", models.URLField(null=True)),
                ("order", models.FloatField(default=1)),
                (
                    "style",
                    models.CharField(
                        choices=[("normal", "normal")],
                        default="normal",
                        max_length=50,
                    ),
                ),
                ("icon_name", models.CharField(max_length=255, null=True)),
                ("icon_path", models.URLField(null=True)),
                (
                    "extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extensions.extension",
                    ),
                ),
                (
                    "required_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.role",
                    ),
                ),
                ("sub_items", models.ManyToManyField(to="menus.menuitem")),
            ],
            options={
                "unique_together": {("name", "extension")},
            },
            bases=(models.Model, collectivo.utils.models.RegisterMixin),
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extensions.extension",
                    ),
                ),
                ("items", models.ManyToManyField(to="menus.menuitem")),
            ],
            options={
                "unique_together": {("name", "extension")},
            },
            bases=(models.Model, collectivo.utils.models.RegisterMixin),
        ),
    ]
