# Generated by Django 4.1.7 on 2023-02-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='action',
            field=models.CharField(choices=[('component', 'component'), ('link', 'link')], default='component', max_length=50, null=True),
        ),
    ]
