# Generated by Django 4.1.7 on 2023-02-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menuitem_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='component_name',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='link_source',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='action_target',
            new_name='target',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='action',
        ),
    ]
