# Generated by Django 4.1.7 on 2023-05-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menuitem_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='target',
            field=models.CharField(choices=[('main', 'main'), ('blank', 'blank'), ('iframe', 'iframe'), ('component', 'component')], default='main', max_length=50),
        ),
    ]
