# Generated by Django 4.1.6 on 2023-02-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_title', models.CharField(blank=True, max_length=30)),
                ('first_shift_date', models.DateField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('fixed', 'fixed'), ('open', 'open')], default='fixed', help_text='Type of shift. Fixed shifts are set automatically every month to one or many users. Open shifts are not addressed to a user yet.', max_length=5)),
                ('shift_week', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', help_text='A month is divided in four shift weeks: A, B, C, D', max_length=1)),
                ('starting_date_time', models.DateTimeField()),
                ('duration', models.FloatField(default=3)),
                ('end_date_time', models.DateTimeField()),
                ('required_users', models.PositiveSmallIntegerField(default='2')),
                ('shift_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', help_text='Shift days are necessary for fixed shifts to registeri.e. every monday on Week A', max_length=10)),
                ('additional_info_general', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_user', models.CharField(blank=True, max_length=30)),
                ('attended', models.BooleanField(default=False)),
                ('additional_info_individual', models.TextField(max_length=300)),
                ('general_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.generalshift')),
            ],
        ),
    ]
