# Generated by Django 4.1.9 on 2023-07-04 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('starting_time', models.TimeField(blank=True, null=True)),
                ('ending_time', models.TimeField(blank=True, null=True)),
                ('required_users', models.PositiveSmallIntegerField(default=1)),
                ('shift_points', models.FloatField(default=1, help_text='Number of points that can be gained by doing this shift.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('repeat', models.CharField(choices=[('none', 'No repetition'), ('abcd', 'Every fourth week (ABCD)')], default='none', max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('repeat_start', models.DateField(blank=True, null=True)),
                ('repeat_end', models.DateField(blank=True, null=True)),
                ('abcd_week', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='The weeks of a year are divided into four groups: A, B, C, D', max_length=1, null=True, verbose_name='Shift week')),
                ('abcd_day', models.CharField(blank=True, choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', help_text='The day of the week the shift takes place, i.e. every Monday on Week A.', max_length=10, null=True, verbose_name='Shift day')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shift_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('jumper', 'Jumper: Do shifts without repetition.'), ('abcd', 'Regular: Do a shift that repeats every four weeks.')], default='none', max_length=30)),
                ('shift_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_weeks', models.PositiveSmallIntegerField(default=4)),
                ('shift_per_month', models.PositiveSmallIntegerField(default=1)),
                ('shift_hours', models.PositiveSmallIntegerField(default=3)),
                ('shift_points_per_shift', models.PositiveSmallIntegerField(default=1)),
                ('shift_points_period_in_days', models.PositiveSmallIntegerField(default=30)),
                ('shift_points_per_period', models.PositiveSmallIntegerField(default=1)),
                ('shift_points_subsbtraction_day', models.PositiveSmallIntegerField(default=1)),
                ('disable_shift_points', models.BooleanField(default=True)),
                ('disable_attendance', models.BooleanField(default=True)),
                ('disable_shift_replacement', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shiftprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shift')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalShiftSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('shift_weeks', models.PositiveSmallIntegerField(default=4)),
                ('shift_per_month', models.PositiveSmallIntegerField(default=1)),
                ('shift_hours', models.PositiveSmallIntegerField(default=3)),
                ('shift_points_per_shift', models.PositiveSmallIntegerField(default=1)),
                ('shift_points_period_in_days', models.PositiveSmallIntegerField(default=30)),
                ('shift_points_per_period', models.PositiveSmallIntegerField(default=1)),
                ('shift_points_subsbtraction_day', models.PositiveSmallIntegerField(default=1)),
                ('disable_shift_points', models.BooleanField(default=True)),
                ('disable_attendance', models.BooleanField(default=True)),
                ('disable_shift_replacement', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shift settings',
                'verbose_name_plural': 'historical shift settingss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShiftProfile',
            fields=[
                ('type', models.CharField(choices=[('jumper', 'Jumper: Do shifts without repetition.'), ('abcd', 'Regular: Do a shift that repeats every four weeks.')], default='none', max_length=30)),
                ('shift_points', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shift profile',
                'verbose_name_plural': 'historical shift profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShiftAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shifts.shiftprofile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'historical shift assignment',
                'verbose_name_plural': 'historical shift assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShift',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('starting_time', models.TimeField(blank=True, null=True)),
                ('ending_time', models.TimeField(blank=True, null=True)),
                ('required_users', models.PositiveSmallIntegerField(default=1)),
                ('shift_points', models.FloatField(default=1, help_text='Number of points that can be gained by doing this shift.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('repeat', models.CharField(choices=[('none', 'No repetition'), ('abcd', 'Every fourth week (ABCD)')], default='none', max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('repeat_start', models.DateField(blank=True, null=True)),
                ('repeat_end', models.DateField(blank=True, null=True)),
                ('abcd_week', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='The weeks of a year are divided into four groups: A, B, C, D', max_length=1, null=True, verbose_name='Shift week')),
                ('abcd_day', models.CharField(blank=True, choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', help_text='The day of the week the shift takes place, i.e. every Monday on Week A.', max_length=10, null=True, verbose_name='Shift day')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shift',
                'verbose_name_plural': 'historical shifts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
