# Generated by Django 4.1.7 on 2023-02-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='shift_end_time',
            new_name='shift_ending_time',
        ),
    ]
