# Generated by Django 4.1.7 on 2023-03-15 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='ShiftAssignment',
        ),
        migrations.RenameModel(
            old_name='ShiftUser',
            new_name='ShiftProfile',
        ),
    ]
