# Generated by Django 4.1.6 on 2023-02-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualshift',
            name='id_general_shift',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
