# Generated by Django 4.1.9 on 2023-07-04 08:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalShiftAssignment',
            new_name='HistoricalShiftSlot',
        ),
        migrations.RenameModel(
            old_name='ShiftAssignment',
            new_name='ShiftSlot',
        ),
        migrations.AlterModelOptions(
            name='historicalshiftslot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical shift slot', 'verbose_name_plural': 'historical shift slots'},
        ),
    ]
