# Generated by Django 4.1.6 on 2023-02-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_individualshift_id_general_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualshift',
            name='id_general_shift',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
