# Generated by Django 4.1.9 on 2023-07-04 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0002_rename_historicalshiftassignment_historicalshiftslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshiftslot',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='shiftslot',
            name='assigned_user',
        ),
        migrations.AddField(
            model_name='historicalshiftslot',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftslot',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftslot',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='shifts.shift'),
        ),
    ]
