# Generated by Django 4.1.6 on 2023-02-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_individualshift_id_general_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftuser',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
