# Generated by Django 4.1.9 on 2023-07-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_remove_historicalshiftslot_assigned_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshift',
            name='required_users',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='required_users',
        ),
    ]
