# Generated by Django 4.1.6 on 2023-02-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shiftuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualshift',
            name='id_general_shift',
        ),
        migrations.AlterField(
            model_name='individualshift',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftuser'),
        ),
    ]
