# Generated by Django 4.1.6 on 2023-02-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_remove_individualshift_id_general_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalshift',
            name='required_users',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='individualshift',
            name='assigned_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftuser'),
        ),
    ]
