# Generated by Django 4.1.6 on 2023-02-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_generalshift_required_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalshift',
            name='shift_type',
            field=models.CharField(choices=[('regular', 'regular'), ('once', 'once')], default='fixed', help_text='Type of shift. Either shifts happen on a regular basis. Or they happen only once.', max_length=30),
        ),
    ]
