# Generated by Django 4.1.8 on 2023-04-21 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakUser',
            fields=[
                ('uuid', models.UUIDField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='keycloak', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
