# Generated by Django 4.1.8 on 2023-04-21 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keycloak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='keycloak', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keycloakuser',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
