# Generated by Django 4.1.9 on 2023-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coresettings_display_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermissiongroup',
            name='users_custom',
            field=models.BooleanField(default=True, help_text='If checked, users can be added to this group manually.', verbose_name='Custom users'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='users_custom',
            field=models.BooleanField(default=True, help_text='If checked, users can be added to this group manually.', verbose_name='Custom users'),
        ),
    ]
