# Generated by Django 4.1.9 on 2023-06-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicalpermissiongroup_users_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermissiongroup',
            name='perms_custom',
            field=models.BooleanField(default=True, help_text='If checked, permissions can be added to this group manually.', verbose_name='Custom permissions'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='perms_custom',
            field=models.BooleanField(default=True, help_text='If checked, permissions can be added to this group manually.', verbose_name='Custom permissions'),
        ),
    ]
