# Generated by Django 4.1.7 on 2023-04-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_historicalinvoice_historicalitemtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotzappInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotzapp_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lotzapp', to='payments.invoice')),
            ],
        ),
    ]
