# Generated by Django 4.1.8 on 2023-04-17 13:38

import collectivo.utils.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotzapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotzappSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotzapp_url', models.URLField(max_length=255)),
                ('lotzapp_user', models.CharField(max_length=255)),
                ('lotzapp_pass', models.CharField(max_length=255)),
                ('zahlungsmethode_sepa', models.IntegerField(null=True)),
                ('zahlungsmethode_transfer', models.IntegerField(null=True)),
                ('adressgruppe', models.IntegerField(null=True)),
            ],
            bases=(collectivo.utils.models.SingleInstance, models.Model),
        ),
        migrations.CreateModel(
            name='LotzappAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotzapp_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lotzapp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
