# Generated by Django 4.1.8 on 2023-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotzapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotzappsettings',
            old_name='adressgruppe',
            new_name='adressgruppe_eg',
        ),
        migrations.AddField(
            model_name='lotzappsettings',
            name='adressgruppe_verein',
            field=models.IntegerField(null=True),
        ),
    ]
