# Generated by Django 4.1.7 on 2023-03-15 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0002_initial'),
        ('members', '0008_membership_membershipcard_membershipstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMembershipType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('has_shares', models.BooleanField(default=False)),
                ('shares_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('shares_number_custom', models.BooleanField(default=False)),
                ('shares_number_custom_min', models.IntegerField(blank=True, null=True)),
                ('shares_number_standard', models.IntegerField(blank=True, null=True)),
                ('shares_number_social', models.IntegerField(blank=True, null=True)),
                ('has_fees', models.BooleanField(default=False)),
                ('fees_custom', models.BooleanField(default=False)),
                ('fees_repeat_each', models.IntegerField(default=1)),
                ('fees_repeat_unit', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('week', 'week'), ('day', 'day')], default='year', max_length=20)),
                ('fees_custom_min', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_social', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('has_card', models.BooleanField(default=False)),
                ('comembership_max', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comembership_of', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.membershiptype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('welcome_mail', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emails.emailtemplate')),
            ],
            options={
                'verbose_name': 'historical membership type',
                'verbose_name_plural': 'historical membership types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
