# Generated by Django 4.1.7 on 2023-03-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
        ('members', '0008_membership_membershipcard_membershipsubtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='fees_repeat_each',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='fees_repeat_unit',
            field=models.CharField(choices=[('year', 'year'), ('month', 'month')], default='year', max_length=20),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='welcome_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate'),
        ),
    ]
