# Generated by Django 4.1.7 on 2023-03-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_membership_payments_membership_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmembership',
            old_name='shares_not_payed',
            new_name='shares_not_paid',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='shares_not_payed',
            new_name='shares_not_paid',
        ),
    ]
