# Generated by Django 4.1.7 on 2023-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_membershiptype_fees_repeat_each_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembershipSubtype',
            new_name='MembershipStatus',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='subtype',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='membership',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
