# Generated by Django 4.1.7 on 2023-03-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_shares_not_payed_historicalmembership_shares_not_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmembership',
            name='active',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='active',
        ),
    ]
