# Generated by Django 4.1.7 on 2023-03-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_membershipsubtype_membershipstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address_city',
            field=models.CharField(default='Undefined', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='address_country',
            field=models.CharField(default='Undefined', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='address_number',
            field=models.CharField(default='Undefined', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='address_postcode',
            field=models.CharField(default='Undefined', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='address_street',
            field=models.CharField(default='Undefined', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member'),
        ),
    ]
