# Generated by Django 4.1.7 on 2023-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_member_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='fees_repeat_unit',
            field=models.CharField(choices=[('year', 'year'), ('month', 'month'), ('week', 'week'), ('day', 'day')], default='year', max_length=20),
        ),
    ]
