# Generated by Django 4.1.7 on 2023-03-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_historicalmembership_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmembershiptype',
            old_name='shares_price',
            new_name='shares_amount',
        ),
        migrations.RenameField(
            model_name='historicalmembershiptype',
            old_name='shares_number_custom',
            new_name='shares_custom',
        ),
        migrations.RenameField(
            model_name='historicalmembershiptype',
            old_name='shares_number_custom_min',
            new_name='shares_custom_max',
        ),
        migrations.RenameField(
            model_name='historicalmembershiptype',
            old_name='shares_number_social',
            new_name='shares_custom_min',
        ),
        migrations.RenameField(
            model_name='historicalmembershiptype',
            old_name='shares_number_standard',
            new_name='shares_standard',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='shares_price',
            new_name='shares_amount',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='shares_number_custom',
            new_name='shares_custom',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='shares_number_custom_min',
            new_name='shares_custom_max',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='shares_number_social',
            new_name='shares_custom_min',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='shares_number_standard',
            new_name='shares_standard',
        ),
        migrations.AddField(
            model_name='historicalmembershiptype',
            name='shares_standard_social',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='shares_standard_social',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
