# Generated by Django 4.1.7 on 2023-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_rename_shares_price_historicalmembershiptype_shares_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmembershiptype',
            old_name='welcome_mail',
            new_name='email_new_membership',
        ),
        migrations.RenameField(
            model_name='historicalmembershiptype',
            old_name='fees_social',
            new_name='fees_custom_max',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='welcome_mail',
            new_name='email_new_membership',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='fees_social',
            new_name='fees_custom_max',
        ),
        migrations.AddField(
            model_name='historicalmembershiptype',
            name='fees_standard_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='fees_standard_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
