# Generated by Django 4.1.7 on 2023-03-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_profile_remove_subscription_payments_and_more'),
        ('members', '0012_alter_membershiptype_fees_repeat_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipstatus',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='label',
            new_name='name',
        ),
        migrations.AddField(
            model_name='membership',
            name='payments',
            field=models.ManyToManyField(blank=True, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='membership',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='payments.subscription'),
        ),
    ]
