# Generated by Django 4.1.7 on 2023-03-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_user_alter_subscription_user'),
        ('members', '0013_rename_label_membershipstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='payments',
            field=models.ManyToManyField(to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='subscriptions',
            field=models.ManyToManyField(to='payments.subscription'),
        ),
    ]
