# Generated by Django 4.1.7 on 2023-03-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_memberprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmembership',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('number', 'type')},
        ),
    ]
