# Generated by Django 4.1.7 on 2023-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_historicalmembership_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmembershipstatus',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='membershipstatus',
            unique_together={('name', 'type')},
        ),
    ]
