# Generated by Django 4.1.7 on 2023-03-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentprofile_user'),
        ('members', '0019_alter_historicalmembershipstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membershipstatus',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalmembershipstatus',
            name='type',
        ),
        migrations.AlterField(
            model_name='historicalmembership',
            name='number',
            field=models.IntegerField(verbose_name='Membership number'),
        ),
        migrations.AlterField(
            model_name='historicalmembership',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.memberprofile', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='historicalmembershipstatus',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='membership',
            name='number',
            field=models.IntegerField(verbose_name='Membership number'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.memberprofile', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='shares_payments',
            field=models.ManyToManyField(blank=True, related_name='membership_shares', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='membershipstatus',
            name='type',
        ),
    ]
