# Generated by Django 4.1.7 on 2023-02-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
