# Generated by Django 4.1.7 on 2023-03-24 12:52

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMembership',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Membership number')),
                ('started', models.DateField(blank=True, null=True)),
                ('cancelled', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
                ('shares_signed', models.PositiveIntegerField(default=0)),
                ('shares_paid', models.PositiveIntegerField(default=0)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical membership',
                'verbose_name_plural': 'historical memberships',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMembershipCard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical membership card',
                'verbose_name_plural': 'historical membership cards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMembershipStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical membership status',
                'verbose_name_plural': 'historical membership statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMembershipType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('has_shares', models.BooleanField(default=False)),
                ('shares_amount_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('shares_number_custom', models.BooleanField(default=False)),
                ('shares_number_custom_min', models.IntegerField(blank=True, null=True)),
                ('shares_number_custom_max', models.IntegerField(blank=True, null=True)),
                ('shares_number_standard', models.IntegerField(blank=True, null=True)),
                ('shares_number_social', models.IntegerField(blank=True, null=True)),
                ('has_fees', models.BooleanField(default=False)),
                ('fees_amount_custom', models.BooleanField(default=False)),
                ('fees_amount_custom_min', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_custom_max', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_social', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_repeat_each', models.IntegerField(default=1)),
                ('fees_repeat_unit', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('week', 'week'), ('day', 'day')], default='year', max_length=20)),
                ('has_card', models.BooleanField(default=False)),
                ('comembership_max', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical membership type',
                'verbose_name_plural': 'historical membership types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Membership number')),
                ('started', models.DateField(blank=True, null=True)),
                ('cancelled', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
                ('shares_signed', models.PositiveIntegerField(default=0)),
                ('shares_paid', models.PositiveIntegerField(default=0)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('comembership_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.membership')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('has_shares', models.BooleanField(default=False)),
                ('shares_amount_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('shares_number_custom', models.BooleanField(default=False)),
                ('shares_number_custom_min', models.IntegerField(blank=True, null=True)),
                ('shares_number_custom_max', models.IntegerField(blank=True, null=True)),
                ('shares_number_standard', models.IntegerField(blank=True, null=True)),
                ('shares_number_social', models.IntegerField(blank=True, null=True)),
                ('has_fees', models.BooleanField(default=False)),
                ('fees_amount_custom', models.BooleanField(default=False)),
                ('fees_amount_custom_min', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_custom_max', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_social', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_repeat_each', models.IntegerField(default=1)),
                ('fees_repeat_unit', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('week', 'week'), ('day', 'day')], default='year', max_length=20)),
                ('has_card', models.BooleanField(default=False)),
                ('comembership_max', models.IntegerField(blank=True, null=True)),
                ('comembership_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.membershiptype')),
                ('email_new_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate')),
                ('statuses', models.ManyToManyField(blank=True, to='memberships.membershipstatus')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='memberships.membership')),
            ],
        ),
    ]
