# Generated by Django 4.1.7 on 2023-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmembership',
            name='date_started',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_started',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='statuses',
            field=models.ManyToManyField(blank=True, help_text='The statuses that a membership of this type can have.', to='memberships.membershipstatus'),
        ),
    ]
