# Generated by Django 4.1.7 on 2023-03-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipcard',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='historicalmembership',
            name='fees_subscription',
        ),
        migrations.RemoveField(
            model_name='historicalmembershiptype',
            name='email_new_membership',
        ),
        migrations.RemoveField(
            model_name='historicalmembershiptype',
            name='has_card',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='fees_subscription',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='shares_payments',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='email_new_membership',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='has_card',
        ),
        migrations.DeleteModel(
            name='HistoricalMembershipCard',
        ),
        migrations.DeleteModel(
            name='MembershipCard',
        ),
    ]
