# Generated by Django 4.1.7 on 2023-03-29 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_historicalmembership_date_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmembership',
            name='date_started',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_started',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
