# Generated by Django 4.1.9 on 2023-06-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_historicalmembership_date_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembershiptype',
            name='enable_registration',
            field=models.BooleanField(default=False, help_text='Whether users can register for this membership type.', verbose_name='Enable registration'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='enable_registration',
            field=models.BooleanField(default=False, help_text='Whether users can register for this membership type.', verbose_name='Enable registration'),
        ),
    ]
