name: Build Docker Container after Django Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Run only after successful testing
  test_django:
    uses: ./.github/workflows/test.yml
  container_builder:
    runs-on: ubuntu-latest
    needs: [test_django]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        run: |
          docker build \
          -t mila/mach-mit-backend:${GITHUB_SHA::7} \
          -t mila/mach-mit-backend:latest \
          .
