name: Deploy to testing

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: remove old containers
        run: |
          docker compose down
      - name: build containers
        run: |
          docker-compose build
      - name: run containers
        run: |
          docker-compose up -d
    
