name: Release latest to docker hub
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container image
        run: |
          docker build -t milawien/collectivo:latest .
          docker push milawien/collectivo:latest
