name: Release to docker hub
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container image
        run: |
          export VERSION=`python -c "import collectivo; print(collectivo.__version__);"`
          docker build -t milawien/collectivo:pr-${VERSION} .
          docker push milawien/collectivo:pr-${VERSION}
