name: Collectivo Testing

# Controls when the workflow will run
on:
  workflow_call:
  push:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test-docker:
    name: Test docker environement
    runs-on: ubuntu-20.04
    steps:
      - name: Check Credentials
        run: |
          echo ${{ secrets.DOCKERHUB_USER }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: docker-compose up -d db && docker-compose build && docker-compose run --rm collectivo sh -c "python manage.py test && flake8"

  publish-backend:
    runs-on: ubuntu-latest
    needs: [test-docker]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container image
        run: |
          docker build -t milawien/mach-mit-backend:pr-${GITHUB_REF#refs/heads/} .
          docker push milawien/mach-mit-backend:pr-${GITHUB_REF#refs/heads/}

  build-collectivo-ux:
    runs-on: ubuntu-latest
    needs: [test-docker]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get repository
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/MILA-Wien/machmit.git
      - name: Build container image
        run: |
          cd machmit
          docker build -t milawien/mach-mit:pr-${GITHUB_REF#refs/heads/} .
          docker push milawien/mach-mit:pr-${GITHUB_REF#refs/heads/}
